# Generated by Django 4.1.7 on 2023-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('h', 'Health'), ('f', 'Fashion'), ('l', 'Lifestyle')], default='l', max_length=5)),
                ('description', models.TextField(blank=True, default=None)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='posts', to='posts.posttag')),
            ],
        ),
    ]
