# Generated by Django 4.1.7 on 2023-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postcategory_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(blank=True, choices=[('h', 'Health'), ('f', 'Fashion'), ('l', 'Lifestyle')], max_length=50, null=True),
        ),
    ]
