# Generated by Django 4.1.7 on 2023-06-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='l', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_category', to='posts.postcategory'),
        ),
    ]
