# Generated by Django 4.1.7 on 2023-06-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_category', to='posts.postcategory'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
