# Generated by Django 4.1.7 on 2023-05-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_category_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], default='ru', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='books.tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='books.publisher'),
        ),
    ]
