# Generated by Django 4.1.7 on 2023-06-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_publisher_tag_alter_movie_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
