# Generated by Django 4.1.7 on 2023-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=''),
        ),
    ]
