# Generated by Django 4.1.7 on 2023-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/no_image.png', upload_to=''),
        ),
    ]
